language: ruby
before_install:
  - gem install bundler
bundler_args: --without yard guard benchmarks
script: "bundle exec rake ci"
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - rbx-19mode
  - jruby-19mode
  - jruby-head
notifications:
  irc:
    channels:
      - irc.freenode.org#rom-rb
    on_success: never
    on_failure: change
  email:
    recipients:
      - dan.kubb@gmail.com
      - mbj@schirp-dso.com
    on_success: never
    on_failure: change
