language: ruby
before_install: gem install bundler --version 1.3.1  # 1.3.[23] fails
bundler_args: --without yard guard benchmarks
script: "bundle exec rake ci"
rvm:
  - ree
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-18mode
  - rbx-19mode
notifications:
  irc: "irc.freenode.org#datamapper"
  email:
    - mbj@seonic.net
    - dan.kubb@gmail.com
matrix:
  allow_failures:
    - rvm: jruby-head  # yard parser fails
