---
AbcMetricMethodCheck:            { score: 5.0 }
AssignmentInConditionalCheck:    { }
CaseMissingElseCheck:            { }
ClassLineCountCheck:             { line_count: 166 }
ClassNameCheck:                  { pattern: !ruby/regexp '/\A(?:[A-Z]+|[A-Z][a-z](?:[A-Z]?[a-z])+)\z/' }
ClassVariableCheck:              { }
CyclomaticComplexityBlockCheck:  { complexity: 2 }
CyclomaticComplexityMethodCheck: { complexity: 2 }
EmptyRescueBodyCheck:            { }
ForLoopCheck:                    { }
MethodLineCountCheck:            { line_count: 4 }
MethodNameCheck:                 { pattern: !ruby/regexp '/\A(?:[a-z\d](?:_?[a-z\d])+[?!=]?|\[\]=?|==|<=>|<<|[+*&|-])\z/' }
ModuleLineCountCheck:            { line_count: 230 }
ModuleNameCheck:                 { pattern: !ruby/regexp '/\A(?:[A-Z]+|[A-Z][a-z](?:[A-Z]?[a-z])+)\z/' }
ParameterNumberCheck:            { parameter_count: 1 }
